openapi: 3.0.0
info:
  title: Fungicibus Product Service API
  description: API for managing clients orders for products
  version: 1.0.0
servers:
  - url: /api/v1

paths:
  /orders:
    post:
      summary: Create a new order
      operationId: CreateOrder
      description: Create a new order with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        "400":
          description: Request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    # Orders
    CreateOrderItem:
      type: object
      required:
        - userID
        - productID
        - quantity
      properties:
        userID:
          type: string
          description: Unique identifier of the user
          example: 1f3b3eb6-de29-41e8-aa0c-a9e52a33beef
        productID:
          type: string
          description: Unique identifier of the product
          example: a8ca1f88-7abd-4105-b0a9-44484c7155fa
        quantity:
          type: integer
          description: Quantity of the product
          example: 10
    CreateOrderRequest:
      type: object
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/CreateOrderItem"

    # Error
    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ErrorItem"
    ErrorItem:
      type: object
      required:
        - id
        - status
        - detail
        - meta
      properties:
        id:
          type: string
          description: Identificator of a request
          example: bd124f62-27ff-4ed7-ad8b-5df0fa73e2c1
        status:
          type: string
          description: The HTTP status code applicable to this problem, expressed as a string value
          example: "400"
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: Bad commodity name
        source:
          $ref: "#/components/schemas/ErrorSource"
        meta:
          $ref: "#/components/schemas/ErrorMeta"
    ErrorSource:
      type: object
      required:
        - pointer
      properties:
        pointer:
          type: string
          description: a JSON Pointer [RFC6901] to the value in the request document that caused the error
          example: /data/quantity
    ErrorMeta:
      type: object
      properties:
        timestamp:
          type: string
          description: Timestamp of the occurrence of the problem in RFC3339 format
          example: 2025-01-02T15:04:05Z07:00
